export type Movie = {
  title: string
  year: number
  genres: string[]
  runtime: string
  rating: number
  description: string
  poster: string
  backdrop?: string
  country: string[]
  director: string
}

export const MY_MOVIES: Movie[] = [
  {
    title: "Конформист",
    year: 1970,
    genres: ["Drama"],
    runtime: "1h 48m",
    rating: 4.2,
    poster: "/posters/conformist.jpg",
    backdrop: "/backdrops/conformist.jpg",
    description: "Слабовольный итальянец становится прислужником фашистского режима и отправляется за границу, чтобы организовать убийство своего бывшего учителя, ныне политического диссидента.",
    country: ["Germany", "France", "Italy"],
    director: "Bernardo Bertolucci"
  },
  {
    title: "Заводной апельсин",
    year: 1971,
    genres: ["Crime", "Drama", "Science Fiction"],
    runtime: "2h 16m",
    rating: 4.1,
    poster: "/posters/clockwork.jpg",
    backdrop: "/backdrops/clockwork.jpg",
    description: "Жестокий молодой хулиган и его банда бесчинствуют в Британии недалёкого будущего, пока его не задерживают и не подвергают спорному экспериментальному «лечению».",
    country: ["UK", "USA"],
    director: "Stanley Kubrick"
  },
  {
    title: "Кабаре",
    year: 1972,
    genres: ["Romance", "Drama", "Music"],
    runtime: "1h 04m",
    rating: 4.2,
    poster: "/posters/cabaret.jpg",
    backdrop: "/backdrops/cabaret.jpg",
    description: "В берлинском кабаре «Кит-Кат-клуб» 1931 года восторженная певица Салли Боулз и дерзкий конферансье зовут публику к беспечным удовольствиям, пока за стенами клуба набирает силу нацистская партия.",
    country: ["Germany", "USA"],
    director: "Bob Fosse"
  },
  {
    title: "Шёпоты и крики",
    year: 1972,
    genres: ["Drama"],
    runtime: "1h 35m",
    rating: 4.2,
    poster: "/posters/cries.jpg",
    backdrop: "/backdrops/cries.jpg",
    description: "Пока Агнес медленно умирает от рака, её сёстры настолько поглощены собственной болью, что не могут дать ей поддержку, в которой она нуждается.",
    country: ["Sweden"],
    director: "Ingmar Bergman"
  },
  {
    title: "Солярис",
    year: 1972,
    genres: ["Mystery", "Science Fiction", "Drama"],
    runtime: "2h 47m",
    rating: 4.2,
    poster: "/posters/solaris.jpg",
    backdrop: "/backdrops/solaris.jpg",
    description: "Психолог отправляется на станцию, вращающуюся вокруг планеты Солярис, чтобы расследовать смерть учёного и странности в поведении космонавтов, и обнаруживает, что океан планеты материализует подавленные воспоминания и чувства.",
    country: ["USSR"],
    director: "Andrei Tarkovsky"
  },
  {
    title: "Крёстный отец",
    year: 1972,
    genres: ["Crime", "Drama"],
    runtime: "2h 55m",
    rating: 4.5,
    poster: "/posters/godfather.jpg",
    backdrop: "/backdrops/godfather.jpg",
    description: "Хроника вымышленной итало-американской семьи Корлеоне с 1945 по 1955 год: когда на главу клана Вито Корлеоне совершают покушение, его младший сын Майкл встаёт во главе кровавой мести убийцам.",
    country: ["USA"],
    director: "Francis Ford Coppola"
  },
  {
    title: "Долгое прощание",
    year: 1973,
    genres: ["Drama", "Crime", "Mystery"],
    runtime: "1h 52m",
    rating: 4.2,
    poster: "/posters/goodbye.jpg",
    backdrop: "/backdrops/goodbye.jpg",
    description: "В Голливуде 1970-х детектив Филип Марлоу пытается помочь другу, обвинённому в убийстве жены.",
    country: ["USA"],
    director: "Robert Altman"
  },
  {
    title: "Дух улья",
    year: 1973,
    genres: ["Fantasy", "Drama"],
    runtime: "1h 38m",
    rating: 4.2,
    poster: "/posters/spirit.jpg",
    backdrop: "/backdrops/spirit.jpg",
    description: "В 1940 году, вскоре после окончания гражданской войны в Испании, девочка с кастильской равнины, посмотрев «Франкенштейна» Джеймса Уэйла, начинает верить словам сестры о том, что чудовище живёт неподалёку в виде духа.",
    country: ["Spain"],
    director: "Víctor Erice"
  },
  {
    title: "Афера",
    year: 1973,
    genres: ["Crime", "Comedy", "Drama"],
    runtime: "2h 09m",
    rating: 4.2,
    poster: "/posters/sting.jpg",
    backdrop: "/backdrops/sting.jpg",
    description: "Два мошенника объединяются, чтобы провернуть грандиозную аферу против безжалостного криминального босса в отместку за убитого друга.",
    country: ["USA"],
    director: "George Roy Hill"
  },
  {
    title: "Китайский квартал",
    year: 1974,
    genres: ["Mystery", "Thriller", "Drama"],
    runtime: "2h 11m",
    rating: 4.3,
    poster: "/posters/chinatown.jpg",
    backdrop: "/backdrops/chinatown.jpg",
    description: "Частный детектив, нанятый, чтобы разоблачить неверного супруга, оказывается втянут в паутину обмана, коррупции и убийства, связанную с водоснабжением Лос-Анджелеса.",
    country: ["USA"],
    director: "Roman Polanski"
  },
  {
    title: "Селин и Жюли совсем заврались",
    year: 1974,
    genres: ["Comedy", "Drama", "Fantasy"],
    runtime: "3h 13m",
    rating: 4.2,
    poster: "/posters/boating.jpg",
    backdrop: "/backdrops/boating.jpg",
    description: "Жюли, мечтательная библиотекарша, знакомится с загадочной фокусницей Селин, и вместе они становятся героинями фантастического приключения с домом с привидениями, волшебными конфетами и детективной мелодрамой.",
    country: ["France"],
    director: "Jacques Rivette"
  },
  {
    title: "Барри Линдон",
    year: 1975,
    genres: ["Drama", "War"],
    runtime: "3h 05m",
    rating: 4.4,
    poster: "/posters/lyndon.jpg",
    backdrop: "/backdrops/lyndon.jpg",
    description: "Ирландский авантюрист благодаря уму, обаянию и беспринципности поднимается по ступеням европейского общества XVIII века, чтобы затем так же стремительно всё потерять.",
    country: ["UK", "USA"],
    director: "Stanley Kubrick"
  },
  {
    title: "Монти Пайтон и Священный Грааль",
    year: 1975,
    genres: ["Comedy", "Adventure", "Fantasy"],
    runtime: "1h 31m",
    rating: 4.1,
    poster: "/posters/python.jpg",
    backdrop: "/backdrops/python.jpg",
    description: "Король Артур и рыцари Круглого стола отправляются в абсурдный малобюджетный поход за Священным Граалем, по пути встречая смертоносных кроликов и упрямых рыцарей.",
    country: ["UK"],
    director: "Terry Gilliam, Terry Jones"
  },
  {
    title: "Пролетая над гнездом кукушки",
    year: 1975,
    genres: ["Drama"],
    runtime: "2h 13m",
    rating: 4.4,
    poster: "/posters/cuckoo.jpg",
    backdrop: "/backdrops/cuckoo.jpg",
    description: "Мелкий преступник симулирует безумие, чтобы отбывать срок в психиатрической лечебнице вместо тюрьмы, и вскоре становится лидером для других пациентов — и врагом для жестокой медсестры, управляющей отделением.",
    country: ["USA"],
    director: "Miloš Forman"
  },
  {
    title: "Выкорми ворона",
    year: 1976,
    genres: ["Drama"],
    runtime: "1h 45m",
    rating: 4.2,
    poster: "/posters/cria.jpg",
    backdrop: "/backdrops/cria.jpg",
    description: "В Мадриде осиротевших сестёр Ирену, Ану и Майте воспитывает суровая тётя Паулина после смерти их матери и отца-военного; Ана, зачарованная темой смерти, замыкается в собственном мире.",
    country: ["Spain"],
    director: "Carlos Saura"
  },
  {
    title: "Сеть",
    year: 1976,
    genres: ["Drama", "Comedy"],
    runtime: "2h 01m",
    rating: 4.3,
    poster: "/posters/network.jpg",
    backdrop: "/backdrops/network.jpg",
    description: "Телекомпания цинично использует нервный срыв ведущего новостей в прямом эфире ради рейтингов, превращая его в пророка народного гнева.",
    country: ["USA"],
    director: "Sidney Lumet"
  },
  {
    title: "Рокки",
    year: 1976,
    genres: ["Drama", "Sport"],
    runtime: "1h 59m",
    rating: 4.1,
    poster: "/posters/rocky.jpg",
    backdrop: "/backdrops/rocky.jpg",
    description: "Никому не известный филадельфийский боксёр получает уникальный шанс — бой за титул чемпиона мира в тяжёлом весе.",
    country: ["USA"],
    director: "John G. Avildsen"
  },
  {
    title: "Таксист",
    year: 1976,
    genres: ["Crime", "Drama"],
    runtime: "1h 54m",
    rating: 4.1,
    poster: "/posters/taxidriver.jpg",
    backdrop: "/backdrops/taxidriver.jpg",
    description: "Психически неустойчивый ветеран Вьетнама работает ночным таксистом в Нью-Йорке, и растущая изоляция и отвращение к городскому пороку толкают его к насилию.",
    country: ["USA"],
    director: "Martin Scorsese"
  },
  {
    title: "3 женщины",
    year: 1977,
    genres: ["Drama"],
    runtime: "2h 04m",
    rating: 4.1,
    poster: "/posters/women.jpg",
    backdrop: "/backdrops/women.jpg",
    description: "Две сотрудницы — тщеславная женщина и неловкая девушка-подросток — становятся соседками по квартире, и их отношения постепенно превращаются во всё более странные.",
    country: ["USA"],
    director: "Robert Altman"
  },
  {
    title: "Колдун",
    year: 1977,
    genres: ["Drama", "Thriller", "Adventure"],
    runtime: "2h 02m",
    rating: 4.3,
    poster: "/posters/sorcerer.jpg",
    backdrop: "/backdrops/sorcerer.jpg",
    description: "Четверо мужчин из разных уголков мира, скрывающихся от прошлого в захолустном южноамериканском городке, соглашаются рискнуть жизнью, перевозя через опасные джунгли ящики со старым динамитом, истекающим нестабильным нитроглицерином.",
    country: ["USA"],
    director: "William Friedkin"
  },
  {
    title: "Осенняя соната",
    year: 1978,
    genres: ["Music", "Drama"],
    runtime: "1h 33m",
    rating: 4.5,
    poster: "/posters/sonata.jpg",
    backdrop: "/backdrops/sonata.jpg",
    description: "После семи лет разлуки Шарлотта Андергаст приезжает в Швецию к дочери Еве; за одну эмоциональную ночь женщины вскрывают старые раны, а затем Шарлотту ждёт ещё один удар — она узнаёт, что её больная дочь Хелена живёт у Евы.",
    country: ["Germany", "Sweden", "UK"],
    director: "Ingmar Bergman"
  },
  {
    title: "Охотник на оленей",
    year: 1978,
    genres: ["Drama", "War"],
    runtime: "3h 03m",
    rating: 4.2,
    poster: "/posters/deer.jpg",
    backdrop: "/backdrops/deer.jpg",
    description: "Война во Вьетнаме разрушает жизни и дружбу трёх металлургов из маленького городка в Пенсильвании.",
    country: ["USA"],
    director: "Michael Cimino"
  },
  {
    title: "Чужой",
    year: 1979,
    genres: ["Horror", "Science Fiction"],
    runtime: "1h 57m",
    rating: 4.2,
    poster: "/posters/alien.jpg",
    backdrop: "/backdrops/alien.jpg",
    description: "Экипаж грузового космического буксира гибнет один за другим после того, как на борт попадает смертоносное инопланетное существо.",
    country: ["UK", "USA"],
    director: "Ridley Scott"
  },
  {
    title: "Апокалипсис сегодня",
    year: 1979,
    genres: ["War", "Drama"],
    runtime: "2h 27m",
    rating: 4.4,
    poster: "/posters/apocalypse.jpg",
    backdrop: "/backdrops/apocalypse.jpg",
    description: "Капитан армии США отправляется вглубь камбоджийских джунглей во время войны во Вьетнаме, чтобы убить полковника-ренегата, возомнившего себя богом.",
    country: ["USA"],
    director: "Francis Ford Coppola"
  },
  {
    title: "Сталкер",
    year: 1979,
    genres: ["Drama", "Science Fiction"],
    runtime: "2h 42m",
    rating: 4.4,
    poster: "/posters/stalker.jpg",
    backdrop: "/backdrops/stalker.jpg",
    description: "Проводник ведёт двух мужчин через Зону — таинственную запретную территорию, которая, по слухам, исполняет самое сокровенное желание того, кто доберётся до её сердца.",
    country: ["USSR"],
    director: "Andrei Tarkovsky"
  },
  {
    title: "Бешеный бык",
    year: 1980,
    genres: ["Drama", "Sport"],
    runtime: "2h 09m",
    rating: 4.2,
    poster: "/posters/bull.jpg",
    backdrop: "/backdrops/bull.jpg",
    description: "Хроника саморазрушительной жизни боксёра-средневеса Джейка Ламотты на ринге и за его пределами.",
    country: ["USA"],
    director: "Martin Scorsese"
  },
  {
    title: "Подводная лодка",
    year: 1981,
    genres: ["War", "Drama"],
    runtime: "2h 29m",
    rating: 4.3,
    poster: "/posters/dasboot.jpg",
    backdrop: "/backdrops/dasboot.jpg",
    description: "Экипаж немецкой подлодки переживает клаустрофобный ужас и изматывающую рутину во время опасного патрулирования Атлантики в годы Второй мировой войны.",
    country: ["West Germany"],
    director: "Wolfgang Petersen"
  },
  {
    title: "Бегущий по лезвию",
    year: 1982,
    genres: ["Thriller", "Drama", "Science Fiction"],
    runtime: "1h 58m",
    rating: 4.1,
    poster: "/posters/blade.jpg",
    backdrop: "/backdrops/blade.jpg",
    description: "В задымлённом антиутопичном Лос-Анджелесе 2019 года охотник за головами Рик Декард возвращается из отставки, чтобы уничтожить четырёх репликантов, сбежавших на Землю в поисках способа продлить свою короткую жизнь.",
    country: ["USA", "Hong Kong", "UK"],
    director: "Ridley Scott"
  },
  {
    title: "Фанни и Александр",
    year: 1982,
    genres: ["Drama", "Fantasy"],
    runtime: "3h 08m",
    rating: 4.4,
    poster: "/posters/fanny.jpg",
    backdrop: "/backdrops/fanny.jpg",
    description: "Брат и сестра из состоятельной шведской театральной семьи переживают радости и невзгоды после того, как их овдовевшая мать выходит замуж за сурового епископа.",
    country: ["Sweden", "France", "West Germany"],
    director: "Ingmar Bergman"
  },
  {
    title: "Пинк Флойд: Стена",
    year: 1982,
    genres: ["Music", "Drama"],
    runtime: "1h 35m",
    rating: 4.1,
    poster: "/posters/floyd.jpg",
    backdrop: "/backdrops/floyd.jpg",
    description: "Измученный рок-музыкант погружается в безумие на фоне физической и социальной изоляции от окружающих.",
    country: ["UK"],
    director: "Alan Parker"
  },
  {
    title: "Нечто",
    year: 1982,
    genres: ["Horror", "Science Fiction"],
    runtime: "1h 49m",
    rating: 4.3,
    poster: "/posters/thething.jpg",
    backdrop: "/backdrops/thething.jpg",
    description: "Меняющий форму инопланетный организм терроризирует изолированную антарктическую исследовательскую станцию, заставляя участников экспедиции подозревать друг друга.",
    country: ["USA"],
    director: "John Carpenter"
  },
  {
    title: "Лицо со шрамом",
    year: 1983,
    genres: ["Crime", "Drama"],
    runtime: "2h 50m",
    rating: 4.1,
    poster: "/posters/scarface.jpg",
    backdrop: "/backdrops/scarface.jpg",
    description: "Кубинский беженец проходит путь от посудомойщика до безжалостного наркобарона Майами, пока его не губят собственная жадность и паранойя.",
    country: ["USA"],
    director: "Brian De Palma"
  },
  {
    title: "Амадей",
    year: 1984,
    genres: ["Drama", "History", "Music"],
    runtime: "2h 40m",
    rating: 4.4,
    poster: "/posters/amadeus.jpg",
    backdrop: "/backdrops/amadeus.jpg",
    description: "Дисциплинированный итальянский композитор Антонио Сальери сгорает от зависти и обиды к гедонисту и невероятно одарённому молодому зальцбургскому композитору Вольфгангу Амадею Моцарту.",
    country: ["USA"],
    director: "Miloš Forman"
  },
  {
    title: "Потоки любви",
    year: 1984,
    genres: ["Drama"],
    runtime: "2h 21m",
    rating: 4.2,
    poster: "/posters/love.jpg",
    backdrop: "/backdrops/love.jpg",
    description: "Двое тесно связанных, душевно израненных брата и сестры воссоединяются после многих лет разлуки.",
    country: ["USA"],
    director: "John Cassavetes"
  },
  {
    title: "Однажды в Америке",
    year: 1984,
    genres: ["Crime", "Drama"],
    runtime: "3h 49m",
    rating: 4.2,
    poster: "/posters/america.jpg",
    backdrop: "/backdrops/america.jpg",
    description: "Постаревший гангстер возвращается на Лоуэр-Ист-Сайд, где полвека назад вырос вместе с друзьями, ставшими впоследствии частью его жизни еврейского мафиози.",
    country: ["USA", "Italy"],
    director: "Sergio Leone"
  },
  {
    title: "Париж, Техас",
    year: 1984,
    genres: ["Drama"],
    runtime: "2h 25m",
    rating: 4.4,
    poster: "/posters/texas.jpg",
    backdrop: "/backdrops/texas.jpg",
    description: "Человек выходит из пустыни, не помня, кто он; его брат находит его и помогает восстановить память о жизни, которую тот оставил, исчезнув четыре года назад.",
    country: ["UK", "Germany", "France"],
    director: "Wim Wenders"
  },
  {
    title: "Назад в будущее",
    year: 1985,
    genres: ["Adventure", "Comedy", "Science Fiction"],
    runtime: "1h 56m",
    rating: 4.2,
    poster: "/posters/backfuture.jpg",
    backdrop: "/backdrops/backfuture.jpg",
    description: "Подросток случайно отправляется на тридцать лет в прошлое на машине времени из DeLorean, где должен устроить так, чтобы его будущие родители влюбились друг в друга.",
    country: ["USA"],
    director: "Robert Zemeckis"
  },
  {
    title: "Иди и смотри",
    year: 1985,
    genres: ["War", "Drama"],
    runtime: "2h 22m",
    rating: 4.6,
    poster: "/posters/comesee.jpg",
    backdrop: "/backdrops/comesee.jpg",
    description: "Юный белорусский мальчик уходит к партизанам и становится свидетелем зверств нацистской оккупации, теряя детскую невинность от увиденного.",
    country: ["USSR"],
    director: "Elem Klimov"
  },
  {
    title: "Взвод",
    year: 1986,
    genres: ["War", "Drama"],
    runtime: "2h 00m",
    rating: 4.0,
    poster: "/posters/platoon.jpg",
    backdrop: "/backdrops/platoon.jpg",
    description: "Молодой американский солдат во Вьетнаме сталкивается с моральным хаосом войны, оказавшись между двумя сержантами, воплощающими её лучшую и худшую стороны.",
    country: ["USA", "UK"],
    director: "Oliver Stone"
  },
  {
    title: "Останься со мной",
    year: 1986,
    genres: ["Drama", "Crime"],
    runtime: "1h 29m",
    rating: 4.2,
    poster: "/posters/stand.jpg",
    backdrop: "/backdrops/stand.jpg",
    description: "Узнав, что неподалёку погиб их ровесник, четверо мальчишек отправляются посмотреть на тело; путешествие через свалку и болото пиявок превращается для них в путь самопознания и взросления.",
    country: ["USA"],
    director: "Rob Reiner"
  },
  {
    title: "Вселяющий страх",
    year: 1986,
    genres: ["Mystery", "Drama", "Thriller", "Crime"],
    runtime: "1h 49m",
    rating: 4.1,
    poster: "/posters/terrorizers.jpg",
    backdrop: "/backdrops/terrorizers.jpg",
    description: "Жизни случайного фотографа, писательницы и её мужа-карьериста переплетаются в загадочной мозаике городского отчуждения тайбэйской «новой волны».",
    country: ["Taiwan"],
    director: "Edward Yang"
  },
  {
    title: "Зелёный луч",
    year: 1986,
    genres: ["Drama", "Romance"],
    runtime: "1h 39m",
    rating: 4.2,
    poster: "/posters/ray.jpg",
    backdrop: "/backdrops/ray.jpg",
    description: "Одинокая парижанка пытается справиться со своей изоляцией и тревогами во время затянувшегося летнего отпуска.",
    country: ["France"],
    director: "Éric Rohmer"
  },
  {
    title: "Жертвоприношение",
    year: 1986,
    genres: ["Drama"],
    runtime: "2h 29m",
    rating: 4.3,
    poster: "/posters/sacrifice.jpg",
    backdrop: "/backdrops/sacrifice.jpg",
    description: "Александр, журналист, философ и бывший актёр, празднует день рождения с друзьями и семьёй, когда объявляют о начале ядерной войны.",
    country: ["Sweden"],
    director: "Andrei Tarkovsky"
  },
  {
    title: "До свидания, дети",
    year: 1987,
    genres: ["Drama", "War"],
    runtime: "1h 45m",
    rating: 4.2,
    poster: "/posters/au.jpg",
    backdrop: "/backdrops/au.jpg",
    description: "Трогательная история дружбы и тяжёлой утраты двух мальчиков в оккупированной нацистами Франции: в католическом интернате беспечная дружба сверстников обрывается, когда раскрывается тайна.",
    country: ["Germany", "France"],
    director: "Louis Malle"
  },
  {
    title: "Цельнометаллическая оболочка",
    year: 1987,
    genres: ["War", "Drama"],
    runtime: "1h 56m",
    rating: 4.2,
    poster: "/posters/fullmetal.jpg",
    backdrop: "/backdrops/fullmetal.jpg",
    description: "Взвод новобранцев морской пехоты проходит жестокую муштру, прежде чем оказаться в хаосе войны во Вьетнаме.",
    country: ["UK", "USA"],
    director: "Stanley Kubrick"
  },
  {
    title: "Принцесса-невеста",
    year: 1987,
    genres: ["Adventure", "Comedy", "Romance"],
    runtime: "1h 38m",
    rating: 4.1,
    poster: "/posters/princessbride.jpg",
    backdrop: "/backdrops/princessbride.jpg",
    description: "Сказочная история истинной любви и больших приключений: бывший работник фермы, ставший пиратом, спасает свою возлюбленную от нежеланного королевского брака.",
    country: ["USA"],
    director: "Rob Reiner"
  },
  {
    title: "Небо над Берлином",
    year: 1987,
    genres: ["Drama", "Fantasy", "Romance"],
    runtime: "2h 8m",
    rating: 4.3,
    poster: "/posters/wings.jpg",
    backdrop: "/backdrops/wings.jpg",
    description: "Два ангела, Дамиэль и Кассиэль, незримо парят над улицами Берлина, наблюдая за людьми, пока Дамиэль не влюбляется в одинокую цирковую артистку Марион и не мечтает обрести смертную человеческую жизнь.",
    country: ["Germany", "France"],
    director: "Wim Wenders"
  },
  {
    title: "Новый кинотеатр «Парадизо»",
    year: 1988,
    genres: ["Drama", "Romance"],
    runtime: "2h 35m",
    rating: 4.5,
    poster: "/posters/paradiso.jpg",
    backdrop: "/backdrops/paradiso.jpg",
    description: "Кинорежиссёр вспоминает детство, когда влюбился в кино в деревенском кинотеатре и подружился с его киномехаником.",
    country: ["Italy", "France"],
    director: "Giuseppe Tornatore"
  },
  {
    title: "Крепкий орешек",
    year: 1988,
    genres: ["Action", "Thriller"],
    runtime: "2h 12m",
    rating: 4.0,
    poster: "/posters/diehard.jpg",
    backdrop: "/backdrops/diehard.jpg",
    description: "Нью-йоркский полицейский в одиночку сражается с террористами, захватившими небоскрёб в Лос-Анджелесе во время рождественской вечеринки.",
    country: ["USA"],
    director: "John McTiernan"
  },
  {
    title: "Пейзаж в тумане",
    year: 1988,
    genres: ["Drama"],
    runtime: "2h 05m",
    rating: 4.4,
    poster: "/posters/mist.jpg",
    backdrop: "/backdrops/mist.jpg",
    description: "Двое греческих детей отправляются на поиски отца, который, как им сказали, живёт в Германии.",
    country: ["France", "Greece", "Italy"],
    director: "Theo Angelopoulos"
  },
  {
    title: "Человек дождя",
    year: 1988,
    genres: ["Drama"],
    runtime: "2h 14m",
    rating: 3.9,
    poster: "/posters/rainman.jpg",
    backdrop: "/backdrops/rainman.jpg",
    description: "Узнав о смерти отца, торговец автомобилями Чарли Бэббит обнаруживает, что у него есть старший брат-аутист Рэймонд, которому досталось всё семейное наследство; поездка через всю страну меняет жизни обоих братьев.",
    country: ["USA"],
    director: "Barry Levinson"
  },
  {
    title: "Общество мёртвых поэтов",
    year: 1989,
    genres: ["Drama"],
    runtime: "2h 09m",
    rating: 4.3,
    poster: "/posters/society.jpg",
    backdrop: "/backdrops/society.jpg",
    description: "В элитной старомодной школе Новой Англии увлечённый учитель литературы вдохновляет учеников бросить вызов условностям и ловить момент, вызывая недовольство сурового директора.",
    country: ["USA"],
    director: "Peter Weir"
  },
  {
    title: "Повар, вор, его жена и её любовник",
    year: 1989,
    genres: ["Crime", "Drama"],
    runtime: "2h 04m",
    rating: 4.2,
    poster: "/posters/cook.jpg",
    backdrop: "/backdrops/cook.jpg",
    description: "Жена жестокого преступника находит утешение в объятиях доброго постоянного гостя ресторана своего мужа.",
    country: ["France", "UK"],
    director: "Peter Greenaway"
  },
  {
    title: "Славные парни",
    year: 1990,
    genres: ["Crime", "Drama"],
    runtime: "2h 25m",
    rating: 4.5,
    poster: "/posters/fellas.jpg",
    backdrop: "/backdrops/fellas.jpg",
    description: "Подлинная история Генри Хилла, наполовину ирландца, наполовину сицилийца из Бруклина, которого с детства привечают бандиты по соседству и который под крылом Джимми Конуэя поднимается по карьерной лестнице мафиозной семьи.",
    country: ["USA"],
    director: "Martin Scorsese"
  },
  {
    title: "Любовники с Нового моста",
    year: 1991,
    genres: ["Drama", "Romance"],
    runtime: "2h 06m",
    rating: 4.2,
    poster: "/posters/bridge.jpg",
    backdrop: "/backdrops/bridge.jpg",
    description: "На закрытом для ремонта старейшем мосту Парижа, Пон-Нёф, разворачивается история любви двух бродяг — Алекса, циркача, зависимого от алкоголя и седативных, и Мишель, художницы, оказавшейся на улице из-за разрыва отношений и постепенно слепнущей.",
    country: ["France"],
    director: "Leos Carax"
  },
  {
    title: "Молчание ягнят",
    year: 1991,
    genres: ["Crime", "Thriller", "Horror", "Drama"],
    runtime: "1h 59m",
    rating: 4.3,
    poster: "/posters/lambs.jpg",
    backdrop: "/backdrops/lambs.jpg",
    description: "Курсантку академии ФБР Клэрис Старлинг отправляют на допрос блестящего психиатра и маньяка-каннибала доктора Ганнибала Лектера, отбывающего пожизненный срок: её начальник надеется, что Лектер поможет раскрыть дело, а молодая привлекательная женщина станет приманкой, чтобы разговорить его.",
    country: ["USA"],
    director: "Jonathan Demme"
  },
  {
    title: "Тельма и Луиза",
    year: 1991,
    genres: ["Drama", "Adventure", "Crime", "Thriller"],
    runtime: "2h 10m",
    rating: 4.2,
    poster: "/posters/thelma.jpg",
    backdrop: "/backdrops/thelma.jpg",
    description: "Решив устроить короткий отдых от унылой повседневности, близкие подруги Тельма и Луиза отправляются в поездку на выходные, которая оборачивается чередой непредвиденных преступлений; став беглянками, женщины заново открывают силу своей дружбы.",
    country: ["UK", "USA"],
    director: "Ridley Scott"
  },
  {
    title: "И жизнь продолжается…",
    year: 1992,
    genres: ["Drama", "Adventure"],
    runtime: "1h 35m",
    rating: 4.3,
    poster: "/posters/life.jpg",
    backdrop: "/backdrops/life.jpg",
    description: "После землетрясения в Гилане кинорежиссёр и его сын едут в разрушенный район на поиски актёров фильма, который он снимал там несколько лет назад, и видят, что даже потерявшие всё люди сохраняют надежду и стремление жить полной жизнью.",
    country: ["Iran"],
    director: "Abbas Kiarostami"
  },
  {
    title: "Бешеные псы",
    year: 1992,
    genres: ["Crime", "Thriller"],
    runtime: "1h 39m",
    rating: 4.1,
    poster: "/posters/dogs.jpg",
    backdrop: "/backdrops/dogs.jpg",
    description: "Проваленное ограбление наводит на мысль об осведомителе в полиции, и напряжение нарастает на складе после налёта: выжившие — ветеран мистер Уайт, новичок мистер Оранж, психопат-условно-досрочник мистер Блонд, склочный мистер Розовый и Хороший Парень Эдди — пытаются понять, кто предатель.",
    country: ["USA"],
    director: "Quentin Tarantino"
  },
  {
    title: "Непрощённый",
    year: 1992,
    genres: ["Western", "Drama"],
    runtime: "2h 11m",
    rating: 4.1,
    poster: "/posters/unforgiven.jpg",
    backdrop: "/backdrops/unforgiven.jpg",
    description: "Постаревший отставной преступник берётся за последнее дело об охоте за наградой, и ему приходится снова встретиться лицом к лицу с тем жестоким человеком, которым он когда-то был.",
    country: ["USA"],
    director: "Clint Eastwood"
  },
  {
    title: "Во имя отца",
    year: 1993,
    genres: ["Drama", "Crime"],
    runtime: "2h 13m",
    rating: 4.1,
    poster: "/posters/thefather.jpg",
    backdrop: "/backdrops/thefather.jpg",
    description: "Молодого ирландца несправедливо сажают в тюрьму за теракт ИРА, которого он не совершал, а его отец оказывается за решёткой вместе с ним в борьбе за восстановление их доброго имени.",
    country: ["UK", "Ireland"],
    director: "Jim Sheridan"
  },
  {
    title: "Парк юрского периода",
    year: 1993,
    genres: ["Adventure", "Science Fiction"],
    runtime: "2h 07m",
    rating: 4.0,
    poster: "/posters/jurassic.jpg",
    backdrop: "/backdrops/jurassic.jpg",
    description: "Тематический парк с клонированными динозаврами погружается в хаос после отказа систем безопасности.",
    country: ["USA"],
    director: "Steven Spielberg"
  },
  {
    title: "Список Шиндлера",
    year: 1993,
    genres: ["Drama", "History", "War"],
    runtime: "3h 15m",
    rating: 4.3,
    poster: "/posters/list.jpg",
    backdrop: "/backdrops/list.jpg",
    description: "Немецкий бизнесмен постепенно проникается сочувствием к своим еврейским рабочим, став свидетелем их преследований, и в итоге рискует всем, чтобы спасти больше тысячи жизней во время Холокоста.",
    country: ["USA"],
    director: "Steven Spielberg"
  },
  {
    title: "Три цвета: Синий",
    year: 1993,
    genres: ["Drama"],
    runtime: "1h 38m",
    rating: 4.2,
    poster: "/posters/blue.jpg",
    backdrop: "/backdrops/blue.jpg",
    description: "Жена знаменитого композитора выживает в автокатастрофе, унёсшей жизни мужа и дочери, и, оставшись одна, пытается сбросить старую личность и обрести свободу, но обнаруживает, что неразрывно связана с другими людьми, включая любовницу мужа, о существовании которой не подозревала.",
    country: ["France", "Poland", "Switzerland"],
    director: "Krzysztof Kieślowski"
  },
  {
    title: "Чунгкингский экспресс",
    year: 1994,
    genres: ["Comedy", "Drama", "Romance"],
    runtime: "1h 43m",
    rating: 4.3,
    poster: "/posters/express.jpg",
    backdrop: "/backdrops/express.jpg",
    description: "Двое меланхоличных гонконгских полицейских влюбляются: один — в загадочную фигуру из криминального мира, другой — в прекрасную и эфемерную официантку ночного ресторана.",
    country: ["Hong Kong"],
    director: "Wong Kar-Wai"
  },
  {
    title: "Форрест Гамп",
    year: 1994,
    genres: ["Drama", "Romance", "Comedy"],
    runtime: "2h 22m",
    rating: 4.2,
    poster: "/posters/gump.jpg",
    backdrop: "/backdrops/gump.jpg",
    description: "Человек с низким IQ совершает великие поступки и оказывается причастен к значимым историческим событиям, неизменно превосходя все ожидания, но при этом так и не может обрести свою единственную любовь.",
    country: ["USA"],
    director: "Robert Zemeckis"
  },
  {
    title: "Леон",
    year: 1994,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: "1h 50m",
    rating: 4.3,
    poster: "/posters/leon.jpg",
    backdrop: "/backdrops/leon.jpg",
    description: "Наёмный убийца из Нью-Йорка берёт под опеку девочку после убийства её семьи, и между ними возникает странная связь, пока он обучает её своему ремеслу.",
    country: ["France"],
    director: "Luc Besson"
  },
  {
    title: "Криминальное чтиво",
    year: 1994,
    genres: ["Crime", "Drama"],
    runtime: "2h 34m",
    rating: 4.3,
    poster: "/posters/fiction.jpg",
    backdrop: "/backdrops/fiction.jpg",
    description: "Жизни двух наёмных убийц, боксёра, жены гангстера и парочки грабителей закусочной переплетаются в нелинейной истории о насилии и искуплении.",
    country: ["USA"],
    director: "Quentin Tarantino"
  },
  {
    title: "Побег из Шоушенка",
    year: 1994,
    genres: ["Drama"],
    runtime: "2h 22m",
    rating: 4.5,
    poster: "/posters/shawshank.jpg",
    backdrop: "/backdrops/shawshank.jpg",
    description: "Несправедливо осуждённый за убийство банкир заводит крепкую дружбу с сокамерником за долгие годы в тюрьме, втайне готовя побег.",
    country: ["USA"],
    director: "Frank Darabont"
  },
  {
    title: "Перед рассветом",
    year: 1995,
    genres: ["Drama", "Romance"],
    runtime: "1h 41m",
    rating: 4.1,
    poster: "/posters/sunrise.jpg",
    backdrop: "/backdrops/sunrise.jpg",
    description: "Молодой американец и француженка знакомятся в поезде и проводят одну незабываемую ночь, гуляя и разговаривая по Вене.",
    country: ["USA", "Austria", "Switzerland"],
    director: "Richard Linklater"
  },
  {
    title: "Храброе сердце",
    year: 1995,
    genres: ["Drama", "War", "History"],
    runtime: "2h 58m",
    rating: 3.9,
    poster: "/posters/braveheart.jpg",
    backdrop: "/backdrops/braveheart.jpg",
    description: "Шотландский воин поднимает восстание против тирании английского короля, претендующего на шотландский трон.",
    country: ["USA"],
    director: "Mel Gibson"
  },
  {
    title: "Казино",
    year: 1995,
    genres: ["Crime", "Drama"],
    runtime: "2h 58m",
    rating: 4.0,
    poster: "/posters/casino.jpg",
    backdrop: "/backdrops/casino.jpg",
    description: "Судьба директора казино рушится на фоне коррупции мафии, неблагополучного брака и нарастающего насилия друга детства в Лас-Вегасе 1970-х.",
    country: ["USA", "France"],
    director: "Martin Scorsese"
  },
  {
    title: "Падшие ангелы",
    year: 1995,
    genres: ["Crime", "Romance", "Action"],
    runtime: "1h 38m",
    rating: 4.2,
    poster: "/posters/fallen.jpg",
    backdrop: "/backdrops/fallen.jpg",
    description: "Наёмный убийца пытается вырваться из своей жестокой жизни, преодолевая препятствия, несмотря на сопротивление напарницы, тайно в него влюблённой.",
    country: ["Hong Kong"],
    director: "Wong Kar-Wai"
  },
  {
    title: "Схватка",
    year: 1995,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: "2h 50m",
    rating: 4.1,
    poster: "/posters/heat.jpg",
    backdrop: "/backdrops/heat.jpg",
    description: "Опытного профессионального грабителя и неумолимого детектива, охотящегося за ним, ждёт неминуемое взрывное противостояние.",
    country: ["USA"],
    director: "Michael Mann"
  },
  {
    title: "Ненависть",
    year: 1995,
    genres: ["Drama"],
    runtime: "1h 38m",
    rating: 4.5,
    poster: "/posters/lahaine.jpg",
    backdrop: "/backdrops/lahaine.jpg",
    description: "После хаотичной ночи беспорядков в неблагополучном пригороде Парижа трое молодых друзей — Венсан, Юбер и Саид — слоняются по городу в ожидании новостей о здоровье общего друга, тяжело пострадавшего в стычке с полицией.",
    country: ["France"],
    director: "Mathieu Kassovitz"
  },
  {
    title: "Любовное письмо",
    year: 1995,
    genres: ["Romance", "Drama"],
    runtime: "1h 38m",
    rating: 4.1,
    poster: "/posters/letter.jpg",
    backdrop: "/backdrops/letter.jpg",
    description: "Хироко приходит на поминальную службу по своему погибшему в горах жениху Ицуки Фудзии; узнав его школьный адрес, она отправляет туда письмо и неожиданно получает ответ — от одноклассницы покойного, которую тоже зовут Ицуки Фудзии.",
    country: ["Japan"],
    director: "Shunji Iwai"
  },
  {
    title: "Семь",
    year: 1995,
    genres: ["Mystery", "Crime", "Thriller"],
    runtime: "2h 07m",
    rating: 4.4,
    poster: "/posters/seven.jpg",
    backdrop: "/backdrops/seven.jpg",
    description: "Два детектива из отдела убийств ведут отчаянную охоту на серийного маньяка, чьи преступления построены на «семи смертных грехах»; опытный Сомерсет изучает каждый грех, пытаясь проникнуть в сознание убийцы, пока его молодой напарник Миллс скептически относится к этим попыткам.",
    country: ["USA"],
    director: "David Fincher"
  },
  {
    title: "Подозрительные лица",
    year: 1995,
    genres: ["Crime", "Mystery", "Thriller"],
    runtime: "1h 46m",
    rating: 4.2,
    poster: "/posters/suspects.jpg",
    backdrop: "/backdrops/suspects.jpg",
    description: "Единственный выживший после кровавого ограбления рассказывает агенту федеральной службы запутанную историю о мифическом криминальном боссе по имени Кайзер Созе.",
    country: ["USA", "Germany"],
    director: "Bryan Singer"
  },
  {
    title: "Рассекая волны",
    year: 1996,
    genres: ["Drama", "Romance"],
    runtime: "2h 39m",
    rating: 4.1,
    poster: "/posters/waves.jpg",
    backdrop: "/backdrops/waves.jpg",
    description: "В маленькой консервативной шотландской деревне нефтяник оказывается парализован после несчастного случая; его жена, молившаяся за его возвращение, чувствует вину, особенно когда муж убеждает её спать с другими мужчинами.",
    country: ["Denmark", "France", "Netherlands", "Norway", "Sweden"],
    director: "Lars von Trier"
  },
  {
    title: "Фарго",
    year: 1996,
    genres: ["Crime", "Comedy", "Drama", "Thriller"],
    runtime: "1h 38m",
    rating: 4.1,
    poster: "/posters/fargo.jpg",
    backdrop: "/backdrops/fargo.jpg",
    description: "Джерри, продавец машин из маленького городка в Миннесоте, погряз в долгах, но у него есть план: нанять двух бандитов, чтобы похитить его жену и получить выкуп от богатого тестя — никто не должен пострадать, пока не начинают гибнуть люди; за дело берётся беременная начальница полиции Мардж.",
    country: ["UK", "USA"],
    director: "Joel Coen"
  },
  {
    title: "Тайны и ложь",
    year: 1996,
    genres: ["Drama"],
    runtime: "2h 22m",
    rating: 4.3,
    poster: "/posters/secretslies.jpg",
    backdrop: "/backdrops/secretslies.jpg",
    description: "После смерти приёмной матери успешная чернокожая женщина-офтальмолог Гортензия разыскивает родную мать и с удивлением обнаруживает, что ею оказывается Синтия — белая женщина из рабочего класса.",
    country: ["UK", "France"],
    director: "Mike Leigh"
  },
  {
    title: "Разбойник",
    year: 1996,
    genres: ["Crime", "Drama", "Romance"],
    runtime: "2h 01m",
    rating: 4.0,
    poster: "/posters/bandit.jpg",
    backdrop: "/backdrops/bandit.jpg",
    description: "Освобождённый после тридцати пяти лет тюрьмы, постаревший турецкий разбойник возвращается домой и обнаруживает, что его деревни больше нет, а возлюбленная пропала; в Стамбуле он находит хрупкую дружбу с молодым мелким преступником.",
    country: ["Turkey"],
    director: "Yavuz Turgul"
  },
  {
    title: "На игле",
    year: 1996,
    genres: ["Crime", "Drama"],
    runtime: "1h 34m",
    rating: 4.2,
    poster: "/posters/trainspotting.jpg",
    backdrop: "/backdrops/trainspotting.jpg",
    description: "Героиновый наркоман Марк Рентон мечется между плохими идеями и попытками завязать вместе со своими ненадёжными друзьями — Сикбоем, Бегби, Спадом и Томми; после переезда из Эдинбурга в Лондон Марк понимает, что не может убежать от прошлого, когда Бегби и Сикбой находят его снова.",
    country: ["UK"],
    director: "Danny Boyle"
  },
  {
    title: "Умница Уилл Хантинг",
    year: 1997,
    genres: ["Drama"],
    runtime: "2h 07m",
    rating: 4.4,
    poster: "/posters/willhunting.jpg",
    backdrop: "/backdrops/willhunting.jpg",
    description: "Уилл Хантинг — упрямый гений из рабочего квартала, не справляющийся с уроками жизни; после очередной стычки с законом его последним шансом становится профессор психологии, единственный, кто способен до него достучаться.",
    country: ["USA"],
    director: "Gus Van Sant"
  },
  {
    title: "Секреты Лос-Анджелеса",
    year: 1997,
    genres: ["Crime", "Drama", "Mystery"],
    runtime: "2h 18m",
    rating: 4.0,
    poster: "/posters/confidential.jpg",
    backdrop: "/backdrops/confidential.jpg",
    description: "Трое полицейских Лос-Анджелеса с очень разными методами раскрывают сеть коррупции, скрывающуюся за массовым убийством.",
    country: ["USA"],
    director: "Curtis Hanson"
  },
  {
    title: "Жизнь прекрасна",
    year: 1997,
    genres: ["Drama", "Comedy"],
    runtime: "1h 56m",
    rating: 4.3,
    poster: "/posters/lifeisbeautiful.jpg",
    backdrop: "/backdrops/lifeisbeautiful.jpg",
    description: "Отец-еврей с помощью юмора и фантазии пытается оградить маленького сына от ужасов нацистского концлагеря.",
    country: ["Italy"],
    director: "Roberto Benigni"
  },
  {
    title: "Американская история X",
    year: 1998,
    genres: ["Drama"],
    runtime: "1h 59m",
    rating: 4.2,
    poster: "/posters/historyx.jpg",
    backdrop: "/backdrops/historyx.jpg",
    description: "Дерек Винъярд выходит из тюрьмы после трёх лет за убийство двух чернокожих мужчин; рассказ его брата Дэнни раскрывает, как Дерек когда-то был скинхедом и лидером жестокой банды белых националистов, чьи действия сильно повлияли на брата — теперь он порывает с бандой и пытается уберечь Дэнни от того же пути.",
    country: ["USA"],
    director: "Tony Kaye"
  },
  {
    title: "Карты, деньги, два ствола",
    year: 1998,
    genres: ["Comedy", "Crime"],
    runtime: "1h 47m",
    rating: 3.9,
    poster: "/posters/lockstock.jpg",
    backdrop: "/backdrops/lockstock.jpg",
    description: "Четверо лондонских друзей, задолжавших целое состояние жестокому криминальному авторитету, замышляют ограбить соседей, но втягиваются в куда более крупные неприятности.",
    country: ["UK"],
    director: "Guy Ritchie"
  },
  {
    title: "Спасти рядового Райана",
    year: 1998,
    genres: ["War", "Drama"],
    runtime: "2h 49m",
    rating: 4.2,
    poster: "/posters/privateryan.jpg",
    backdrop: "/backdrops/privateryan.jpg",
    description: "После высадки в Нормандии отряд солдат отправляется в тыл врага, чтобы найти десантника, чьи три брата погибли в бою.",
    country: ["USA"],
    director: "Steven Spielberg"
  },
  {
    title: "Большой Лебовски",
    year: 1998,
    genres: ["Comedy", "Crime"],
    runtime: "1h 57m",
    rating: 4.1,
    poster: "/posters/lebowski.jpg",
    backdrop: "/backdrops/lebowski.jpg",
    description: "Невозмутимого лентяя по прозвищу Чувак принимают за миллионера-тёзку, втягивая его в нелепую историю с похищением.",
    country: ["USA", "UK"],
    director: "Joel Coen, Ethan Coen"
  },
  {
    title: "Торжество",
    year: 1998,
    genres: ["Drama"],
    runtime: "1h 41m",
    rating: 4.3,
    poster: "/posters/celebration.jpg",
    backdrop: "/backdrops/celebration.jpg",
    description: "Семья богатого бизнесмена собирается отпраздновать его 60-летие; во время вечера старший сын произносит речь, раскрывающую страшную тайну, и праздник превращается в схватку правды и отрицания.",
    country: ["Denmark", "Sweden"],
    director: "Thomas Vinterberg"
  },
  {
    title: "Шоу Трумана",
    year: 1998,
    genres: ["Comedy", "Drama"],
    runtime: "1h 43m",
    rating: 4.2,
    poster: "/posters/truman.jpg",
    backdrop: "/backdrops/truman.jpg",
    description: "В идеальном приморском городке страховой агент начинает подозревать, что вся его жизнь — постановочное реалити-шоу, за которым наблюдает огромная невидимая аудитория.",
    country: ["USA"],
    director: "Peter Weir"
  },
  {
    title: "Красота по-американски",
    year: 1999,
    genres: ["Drama"],
    runtime: "2h 02m",
    rating: 4.0,
    poster: "/posters/americanb.jpg",
    backdrop: "/backdrops/americanb.jpg",
    description: "Кризис среднего возраста отца семейства из пригорода переворачивает его жизнь, когда он влюбляется в подругу-подростка своей дочери.",
    country: ["USA"],
    director: "Sam Mendes"
  },
  {
    title: "Магнолия",
    year: 1999,
    genres: ["Drama"],
    runtime: "3h 09m",
    rating: 4.2,
    poster: "/posters/magnolia.jpg",
    backdrop: "/backdrops/magnolia.jpg",
    description: "В один случайный день в Долине Сан-Фернандо умирающий отец, молодая жена, сиделка, знаменитый блудный сын, влюблённый полицейский, мальчик-вундеркинд, бывший вундеркинд, ведущий телевикторины и отчуждённая дочь становятся частью одной ослепительной мозаики судеб.",
    country: ["USA"],
    director: "Paul Thomas Anderson"
  },
  {
    title: "Зелёная миля",
    year: 1999,
    genres: ["Drama", "Crime", "Fantasy"],
    runtime: "3h 09m",
    rating: 4.3,
    poster: "/posters/mile.jpg",
    backdrop: "/backdrops/mile.jpg",
    description: "Сверхъестественная история о камере смертников в тюрьме на юге США, где кроткий великан Джон Коффи обладает таинственной способностью исцелять людей; начальник блока Пол Эджкомб, поняв, какой дар у Коффи, отчаянно пытается спасти его от казни.",
    country: ["USA"],
    director: "Frank Darabont"
  },
  {
    title: "Информатор",
    year: 1999,
    genres: ["Drama", "Thriller"],
    runtime: "2h 38m",
    rating: 4.1,
    poster: "/posters/insider.jpg",
    backdrop: "/backdrops/insider.jpg",
    description: "Учёный-химик подвергается личным и профессиональным нападкам после того, как решает дать интервью для разоблачительного репортажа о табачной индустрии.",
    country: ["USA"],
    director: "Michael Mann"
  },
  {
    title: "Матрица",
    year: 1999,
    genres: ["Action", "Science Fiction"],
    runtime: "2h 16m",
    rating: 4.2,
    poster: "/posters/matrix.jpg",
    backdrop: "/backdrops/matrix.jpg",
    description: "Компьютерный хакер узнаёт, что окружающий мир — это симулированная реальность, и присоединяется к восстанию против контролирующих её машин.",
    country: ["USA", "Australia"],
    director: "Lana Wachowski, Lilly Wachowski"
  },
  {
    title: "Шестое чувство",
    year: 1999,
    genres: ["Drama", "Mystery", "Thriller"],
    runtime: "1h 47m",
    rating: 3.9,
    poster: "/posters/sense.jpg",
    backdrop: "/backdrops/sense.jpg",
    description: "Детский психолог, переживающий не лучшие времена, пытается помочь мальчику, утверждающему, что он видит мёртвых и разговаривает с ними.",
    country: ["USA"],
    director: "M. Night Shyamalan"
  },
  {
    title: "Танцующая в темноте",
    year: 2000,
    genres: ["Drama", "Crime"],
    runtime: "2h 20m",
    rating: 4.2,
    poster: "/posters/dancer.jpg",
    backdrop: "/backdrops/dancer.jpg",
    description: "Сельма, чешская иммигрантка, постепенно слепнущая, из последних сил сводит концы с концами ради себя и сына, унаследовавшего ту же болезнь; когда жизнь становится невыносимой, она находит спасение в любви к мюзиклам, придумывая номера под ритмы окружающего мира.",
    country: ["Denmark", "Finland", "France", "Germany", "Iceland", "Netherlands", "Norway", "Sweden"],
    director: "Lars von Trier"
  },
  {
    title: "Помни",
    year: 2000,
    genres: ["Thriller", "Mystery"],
    runtime: "1h 53m",
    rating: 4.2,
    poster: "/posters/memento.jpg",
    backdrop: "/backdrops/memento.jpg",
    description: "Леонард Шелби разыскивает убийцу своей жены, но поиски осложняет редкая неизлечимая форма потери кратковременной памяти: помня всё, что было до травмы, он не может вспомнить, что произошло пятнадцать минут назад, куда он идёт и зачем.",
    country: ["USA"],
    director: "Christopher Nolan"
  },
  {
    title: "Девять королев",
    year: 2000,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: "1h 54m",
    rating: 4.1,
    poster: "/posters/queens.jpg",
    backdrop: "/backdrops/queens.jpg",
    description: "Два мошенника пытаются обмануть коллекционера марок, продав ему лист поддельных редких марок — «девять королев».",
    country: ["Argentina"],
    director: "Fabián Bielinsky"
  },
  {
    title: "Вспоминая титанов",
    year: 2000,
    genres: ["Drama"],
    runtime: "1h 53m",
    rating: 3.9,
    poster: "/posters/titans.jpg",
    backdrop: "/backdrops/titans.jpg",
    description: "После пятнадцати победных сезонов тренера Билла Йоста понижают в должности и заменяют жёстким и принципиальным Германом Буном; два непохожих друг на друга человека учатся преодолевать разногласия и превращают враждующих подростков в чемпионов.",
    country: ["USA"],
    director: "Boaz Yakin"
  },
  {
    title: "Реквием по мечте",
    year: 2000,
    genres: ["Drama"],
    runtime: "1h 42m",
    rating: 4.2,
    poster: "/posters/requiem.jpg",
    backdrop: "/backdrops/requiem.jpg",
    description: "Четыре переплетённые судьбы жителей Бруклина скатываются в зависимость и отчаяние, пока каждый из героев гонится за всё более недостижимой мечтой.",
    country: ["USA"],
    director: "Darren Aronofsky"
  },
  {
    title: "Ритуал",
    year: 2000,
    genres: ["Drama"],
    runtime: "2h 08m",
    rating: 4.3,
    poster: "/posters/ritual.jpg",
    backdrop: "/backdrops/ritual.jpg",
    description: "Разочаровавшийся в профессии режиссёр встречает девушку, у которой есть привычка каждый день повторять «Завтра у меня день рождения», и пытается достучаться до неё через объектив видеокамеры.",
    country: ["Japan"],
    director: "Hideaki Anno"
  },
  {
    title: "Большой куш",
    year: 2000,
    genres: ["Comedy", "Crime"],
    runtime: "1h 42m",
    rating: 3.9,
    poster: "/posters/snatch.jpg",
    backdrop: "/backdrops/snatch.jpg",
    description: "Украденный алмаз запускает цепь хаотичных событий с участием боксёрских промоутеров, похитителей драгоценностей и безжалостного гангстера в криминальном подполье Лондона.",
    country: ["UK", "USA"],
    director: "Guy Ritchie"
  },
  {
    title: "Гармонии Веркмейстера",
    year: 2000,
    genres: ["Drama"],
    runtime: "2h 19m",
    rating: 4.3,
    poster: "/posters/werckmeister.jpg",
    backdrop: "/backdrops/werckmeister.jpg",
    description: "Наивный молодой человек становится свидетелем нарастающего насилия в своём маленьком городке после прибытия туда таинственного циркового аттракциона.",
    country: ["France", "Germany", "Hungary"],
    director: "Béla Tarr"
  },
  {
    title: "Игры разума",
    year: 2001,
    genres: ["Romance", "Drama"],
    runtime: "2h 15m",
    rating: 3.9,
    poster: "/posters/mind.jpg",
    backdrop: "/backdrops/mind.jpg",
    description: "Джон Форбс Нэш-младший, блестящий, но социально неловкий математик, переживает взлёт от громкого научного открытия к международному признанию и падение в пучину безумия; тайная работа в криптографии вовлекает красивого и самоуверенного Нэша в загадочный заговор, и его жизнь превращается в кошмарное и мучительное путешествие к самопознанию.",
    country: ["USA"],
    director: "Ron Howard"
  },
  {
    title: "Амели",
    year: 2001,
    genres: ["Romance", "Comedy"],
    runtime: "2h 02m",
    rating: 4.2,
    poster: "/posters/amelie.jpg",
    backdrop: "/backdrops/amelie.jpg",
    description: "В крошечном парижском кафе застенчивая и очаровательная Амели случайно обнаруживает в себе дар помогать другим и проводит дни, выступая свахой, ангелом-хранителем и доброй феей для окружающих, но, столкнувшись с симпатичным незнакомцем, должна найти в себе смелость стать героиней собственной истории любви.",
    country: ["France", "Germany"],
    director: "Jean-Pierre Jeunet"
  },
  {
    title: "Донни Дарко",
    year: 2001,
    genres: ["Drama", "Fantasy", "Mystery"],
    runtime: "1h 54m",
    rating: 4.0,
    poster: "/posters/donniedarko.jpg",
    backdrop: "/backdrops/donniedarko.jpg",
    description: "Едва избежав странной катастрофы, неуравновешенный подросток начинает видеть гигантского кролика, который подталкивает его к совершению преступлений.",
    country: ["USA"],
    director: "Richard Kelly"
  },
  {
    title: "Малхолланд Драйв",
    year: 2001,
    genres: ["Drama", "Mystery", "Thriller"],
    runtime: "2h 27m",
    rating: 4.3,
    poster: "/posters/mullholland.jpg",
    backdrop: "/backdrops/mullholland.jpg",
    description: "Блондинка Бетти Элмс только приезжает в Голливуд, чтобы стать кинозвездой, и встречает загадочную брюнетку с амнезией; пока девушки пытаются выяснить личность второй женщины, режиссёр Адам Кешер сталкивается с тревожными проблемами во время кастинга для своего нового проекта.",
    country: ["France", "USA"],
    director: "David Lynch"
  },
  {
    title: "Поймай меня, если сможешь",
    year: 2002,
    genres: ["Drama", "Crime"],
    runtime: "2h 21m",
    rating: 4.0,
    poster: "/posters/catch.jpg",
    backdrop: "/backdrops/catch.jpg",
    description: "Реальная история Фрэнка Эбигнейла-младшего, который ещё до 19 лет успешно провернул мошенничество на миллионы долларов, выдавая себя за пилота Pan Am, врача и прокурора; агент ФБР делает своей миссией поймать его, но Фрэнк не только ускользает от поимки, но и наслаждается погоней.",
    country: ["USA"],
    director: "Steven Spielberg"
  },
  {
    title: "Пианист",
    year: 2002,
    genres: ["Drama", "War"],
    runtime: "2h 30m",
    rating: 4.3,
    poster: "/posters/pianist.jpg",
    backdrop: "/backdrops/pianist.jpg",
    description: "Польско-еврейский пианист борется за выживание во время уничтожения варшавского гетто в годы Второй мировой войны.",
    country: ["France", "Germany", "Poland", "UK"],
    director: "Roman Polanski"
  },
  {
    title: "Белый олеандр",
    year: 2002,
    genres: ["Drama"],
    runtime: "1h 49m",
    rating: 3.9,
    poster: "/posters/oleander.jpg",
    backdrop: "/backdrops/oleander.jpg",
    description: "Девочка-подросток проходит через череду приёмных семей после того, как её мать попадает в тюрьму за преступление на почве страсти.",
    country: ["Germany", "USA"],
    director: "Peter Kosminsky"
  },
  {
    title: "Убить Билла. Фильм первый",
    year: 2003,
    genres: ["Crime", "Action"],
    runtime: "1h 51m",
    rating: 4.2,
    poster: "/posters/killbill1.jpg",
    backdrop: "/backdrops/killbill1.jpg",
    description: "Наёмная убийца, застреленная безжалостным боссом Биллом и другими членами их группы убийц, выживает, чтобы спланировать месть.",
    country: ["USA"],
    director: "Quentin Tarantino"
  },
  {
    title: "Вечное сияние чистого разума",
    year: 2004,
    genres: ["Science Fiction", "Romance", "Drama"],
    runtime: "1h 48m",
    rating: 4.2,
    poster: "/posters/eternal.jpg",
    backdrop: "/backdrops/eternal.jpg",
    description: "Джоэл Бэриш, убитый горем после того, как его девушка стирает его из своей памяти с помощью особой процедуры, решает сделать то же самое; но, наблюдая, как воспоминания о ней исчезают, он понимает, что всё ещё любит её, и, возможно, уже слишком поздно всё исправить.",
    country: ["USA"],
    director: "Michel Gondry"
  },
  {
    title: "Отель «Руанда»",
    year: 2004,
    genres: ["Drama", "War", "History"],
    runtime: "2h 01m",
    rating: 4.0,
    poster: "/posters/rwanda.jpg",
    backdrop: "/backdrops/rwanda.jpg",
    description: "Управляющий отелем укрывает более тысячи беженцев во время геноцида в Руанде, используя связи и смекалку, чтобы сохранить им жизнь.",
    country: ["UK", "South Africa", "Italy"],
    director: "Terry George"
  },
  {
    title: "Дневник памяти",
    year: 2004,
    genres: ["Romance", "Drama"],
    runtime: "2h 03m",
    rating: 3.9,
    poster: "/posters/notebook.jpg",
    backdrop: "/backdrops/notebook.jpg",
    description: "Эпическая история любви о пожилом мужчине, который читает вслух женщине, страдающей болезнью Альцгеймера; пожелтевшие страницы дневника оживляют рассказ о паре, разлучённой Второй мировой войной и вновь страстно соединившейся спустя семь лет, после разных жизненных путей.",
    country: ["USA"],
    director: "Nick Cassavetes"
  },
  {
    title: "V значит вендетта",
    year: 2005,
    genres: ["Action", "Drama", "Thriller"],
    runtime: "2h 12m",
    rating: 4.0,
    poster: "/posters/vendetta.jpg",
    backdrop: "/backdrops/vendetta.jpg",
    description: "В антиутопичной будущей Британии под властью фашистского режима таинственный мститель в маске, известный как V, замышляет разжечь революцию с помощью молодой девушки.",
    country: ["USA", "UK", "Germany"],
    director: "James McTeigue"
  },
  {
    title: "Маленькая мисс Счастье",
    year: 2006,
    genres: ["Drama", "Comedy"],
    runtime: "1h 42m",
    rating: 4.2,
    poster: "/posters/sunshine.jpg",
    backdrop: "/backdrops/sunshine.jpg",
    description: "Семья эксцентричных и колоритных персонажей набивается в старый микроавтобус и отправляется в Калифорнию, чтобы маленькая Олив поучаствовала в конкурсе красоты.",
    country: ["USA"],
    director: "Valerie Faris, Jonathan Dayton"
  },
  {
    title: "Лабиринт Фавна",
    year: 2006,
    genres: ["Fantasy", "Drama", "War"],
    runtime: "1h 58m",
    rating: 4.3,
    poster: "/posters/pans.jpg",
    backdrop: "/backdrops/pans.jpg",
    description: "Девочка во франкистской Испании уходит в тёмный сказочный мир, которым правит фавн, где ей предстоит выполнить три опасных испытания.",
    country: ["Mexico", "Spain", "USA"],
    director: "Guillermo del Toro"
  },
  {
    title: "Отступники",
    year: 2006,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: "2h 31m",
    rating: 4.3,
    poster: "/posters/departed.jpg",
    backdrop: "/backdrops/departed.jpg",
    description: "Агент под прикрытием внедряется в ирландскую мафию, пока человек мафии поднимается по службе в полиции — каждый из них пытается разоблачить другого раньше, чем будет раскрыт сам.",
    country: ["USA"],
    director: "Martin Scorsese"
  },
  {
    title: "Жизнь других",
    year: 2006,
    genres: ["Drama", "Thriller"],
    runtime: "2h 17m",
    rating: 4.4,
    poster: "/posters/others.jpg",
    backdrop: "/backdrops/others.jpg",
    description: "Офицер восточногерманской тайной полиции, следящий за драматургом и его возлюбленной, постепенно меняет свою лояльность, всё глубже погружаясь в их жизнь.",
    country: ["Germany"],
    director: "Florian Henckel von Donnersmarck"
  },
  {
    title: "Престиж",
    year: 2006,
    genres: ["Science Fiction", "Drama", "Mystery"],
    runtime: "2h 10m",
    rating: 4.3,
    poster: "/posters/prestige.jpg",
    backdrop: "/backdrops/prestige.jpg",
    description: "Таинственная история двух фокусников, чьё яростное соперничество перерастает в многолетнюю борьбу за превосходство, полную одержимости, обмана и зависти с опасными и смертельными последствиями.",
    country: ["UK", "USA"],
    director: "Christopher Nolan"
  },
  {
    title: "В диких условиях",
    year: 2007,
    genres: ["Adventure", "Drama", "Biography"],
    runtime: "2h 28m",
    rating: 4.0,
    poster: "/posters/thewild.jpg",
    backdrop: "/backdrops/thewild.jpg",
    description: "Окончив колледж, молодой человек раздаёт свои сбережения и автостопом отправляется на Аляску, чтобы жить в дикой природе, полностью отказавшись от прежней жизни.",
    country: ["USA"],
    director: "Sean Penn"
  },
  {
    title: "Старикам тут не место",
    year: 2007,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: "2h 02m",
    rating: 4.3,
    poster: "/posters/oldmen.jpg",
    backdrop: "/backdrops/oldmen.jpg",
    description: "Охотник, наткнувшийся на сорвавшуюся сделку с наркотиками и оставленные деньги, становится мишенью неумолимого философствующего убийцы.",
    country: ["USA"],
    director: "Joel Coen, Ethan Coen"
  },
  {
    title: "Нефть",
    year: 2007,
    genres: ["Drama"],
    runtime: "2h 38m",
    rating: 4.4,
    poster: "/posters/beblood.jpg",
    backdrop: "/backdrops/beblood.jpg",
    description: "Безжалостный старатель-серебродобытчик, ставший нефтяным магнатом, строит империю в Калифорнии начала XX века, а его жадность и паранойя поглощают всех вокруг.",
    country: ["USA"],
    director: "Paul Thomas Anderson"
  },
  {
    title: "Гран Торино",
    year: 2008,
    genres: ["Drama"],
    runtime: "1h 56m",
    rating: 4.0,
    poster: "/posters/torino.jpg",
    backdrop: "/backdrops/torino.jpg",
    description: "Озлобленный ветеран Корейской войны с расистскими взглядами сближается со своими соседями-хмонгами после того, как срывает попытку втянуть в банду их сына-подростка.",
    country: ["USA"],
    director: "Clint Eastwood"
  },
  {
    title: "Синекдоха, Нью-Йорк",
    year: 2008,
    genres: ["Drama"],
    runtime: "2h 04m",
    rating: 4.2,
    poster: "/posters/synecdoche.jpg",
    backdrop: "/backdrops/synecdoche.jpg",
    description: "Театральный режиссёр борется с творческим кризисом и проблемами в личной жизни, пытаясь создать в павильоне точную копию Нью-Йорка в натуральную величину для своей новой постановки.",
    country: ["USA"],
    director: "Charlie Kaufman"
  },
  {
    title: "3 идиота",
    year: 2009,
    genres: ["Comedy", "Drama"],
    runtime: "2h 50m",
    rating: 4.1,
    poster: "/posters/idiots.jpg",
    backdrop: "/backdrops/idiots.jpg",
    description: "Два друга разыскивают давно пропавшего товарища по колледжу — свободомыслящего студента-инженера, бросившего вызов косной системе образования Индии.",
    country: ["India"],
    director: "Rajkumar Hirani"
  },
  {
    title: "Бесславные ублюдки",
    year: 2009,
    genres: ["War", "Drama", "Comedy"],
    runtime: "2h 33m",
    rating: 4.3,
    poster: "/posters/basterds.jpg",
    backdrop: "/backdrops/basterds.jpg",
    description: "Отряд еврейско-американских солдат и хозяйка французского кинотеатра, не зная друг о друге, готовят покушение на верхушку нацистского руководства во время премьеры фильма в Париже.",
    country: ["USA", "Germany"],
    director: "Quentin Tarantino"
  },
  {
    title: "Тайна в его глазах",
    year: 2009,
    genres: ["Thriller", "Drama", "Mystery"],
    runtime: "2h 10m",
    rating: 4.2,
    poster: "/posters/secret.jpg",
    backdrop: "/backdrops/secret.jpg",
    description: "Желая разобраться с многолетней тревогой по поводу одного давнего дела, отставной следователь Бенхамин начинает писать роман по мотивам нераскрытого убийства и изнасилования молодожёнки; ему помогает бывшая коллега, судья Ирене.",
    country: ["Argentina", "Spain"],
    director: "Juan José Campanella"
  },
  {
    title: "Пожары",
    year: 2010,
    genres: ["Drama", "Mystery", "War"],
    runtime: "2h 11m",
    rating: 4.2,
    poster: "/posters/incendies.jpg",
    backdrop: "/backdrops/incendies.jpg",
    description: "Близнецы отправляются на Ближний Восток, чтобы исполнить последнюю волю покойной матери, и раскрывают страшные тайны её прошлого во времена гражданской войны.",
    country: ["Canada", "France"],
    director: "Denis Villeneuve"
  },
  {
    title: "Начало",
    year: 2010,
    genres: ["Action", "Adventure", "Science Fiction"],
    runtime: "2h 28m",
    rating: 4.2,
    poster: "/posters/inception.jpg",
    backdrop: "/backdrops/inception.jpg",
    description: "Кобб, искусный вор, специализирующийся на корпоративном шпионаже через проникновение в подсознание целей, получает шанс вернуть прежнюю жизнь в обмен на выполнение невозможной задачи — «внедрения», то есть подсадки чужой идеи в подсознание цели.",
    country: ["UK", "USA"],
    director: "Christopher Nolan"
  },
  {
    title: "Драйв",
    year: 2011,
    genres: ["Thriller", "Drama", "Crime"],
    runtime: "1h 40m",
    rating: 3.9,
    poster: "/posters/drive.jpg",
    backdrop: "/backdrops/drive.jpg",
    description: "Каскадёр, подрабатывающий водителем для преступников, постепенно сближается с соседкой Айрин и её маленьким сыном Бенисио; когда из тюрьмы выходит муж Айрин и втягивает героя в ограбление на миллион долларов, дело идёт наперекосяк, и теперь Водителю приходится рисковать жизнью, защищая Айрин и Бенисио от мстительных организаторов ограбления.",
    country: ["USA"],
    director: "Nicolas Winding Refn"
  },
  {
    title: "1+1",
    year: 2011,
    genres: ["Drama", "Comedy"],
    runtime: "1h 53m",
    rating: 4.2,
    poster: "/posters/1+1.jpg",
    backdrop: "/backdrops/1+1.jpg",
    description: "Реальная история двух мужчин, которым не суждено было встретиться, — аристократа, парализованного после несчастного случая на параплане, и молодого парня из неблагополучного района.",
    country: ["France"],
    director: "Olivier Nakache, Éric Toledano"
  },
  {
    title: "Воин",
    year: 2011,
    genres: ["Drama", "Action", "Sport"],
    runtime: "2h 20m",
    rating: 4.0,
    poster: "/posters/warrior.jpg",
    backdrop: "/backdrops/warrior.jpg",
    description: "Двое отчуждённых братьев — бывший морпех и учитель, переживающий трудные времена, — оказываются на пути к неизбежному столкновению на турнире по смешанным единоборствам.",
    country: ["USA"],
    director: "Gavin O'Connor"
  },
  {
    title: "Джанго освобождённый",
    year: 2012,
    genres: ["Western", "Drama"],
    runtime: "2h 45m",
    rating: 4.3,
    poster: "/posters/django.jpg",
    backdrop: "/backdrops/django.jpg",
    description: "Освобождённый раб, ставший охотником за головами, отправляется вместе с немецким напарником спасать жену из лап жестокого плантатора в Миссисипи.",
    country: ["USA"],
    director: "Quentin Tarantino"
  },
  {
    title: "Охота",
    year: 2012,
    genres: ["Drama", "Thriller"],
    runtime: "1h 55m",
    rating: 4.3,
    poster: "/posters/hunt.jpg",
    backdrop: "/backdrops/hunt.jpg",
    description: "Учитель ведёт одинокую жизнь, борясь за опеку над сыном; всё постепенно налаживается, пока невинная маленькая ложь не разрушает его новую удачу самым жестоким образом.",
    country: ["Denmark"],
    director: "Thomas Vinterberg"
  },
  {
    title: "12 лет рабства",
    year: 2013,
    genres: ["Drama", "History", "War"],
    runtime: "2h 14m",
    rating: 4.2,
    poster: "/posters/slave.jpg",
    backdrop: "/backdrops/slave.jpg",
    description: "Свободного чернокожего жителя Нью-Йорка похищают и продают в рабство; он переживает мучительные годы на плантации в Луизиане, борясь за возвращение свободы.",
    country: ["USA", "UK"],
    director: "Steve McQueen"
  },
  {
    title: "Пленницы",
    year: 2013,
    genres: ["Thriller", "Crime", "Drama"],
    runtime: "2h 33m",
    rating: 4.3,
    poster: "/posters/prisoners.jpg",
    backdrop: "/backdrops/prisoners.jpg",
    description: "Келлер Довер сталкивается с худшим кошмаром любого родителя: его шестилетняя дочь Анна пропадает вместе с подругой Джой, и с каждой минутой паника нарастает; единственная зацепка — ветхий автодом, ранее замеченный на их улице.",
    country: ["USA"],
    director: "Denis Villeneuve"
  },
  {
    title: "Гонка",
    year: 2013,
    genres: ["Action", "Drama", "Sport"],
    runtime: "2h 03m",
    rating: 3.9,
    poster: "/posters/rush.jpg",
    backdrop: "/backdrops/rush.jpg",
    description: "Яростное соперничество «Формулы-1» 1970-х между дисциплинированным австрийским гонщиком Ники Лаудой и беспечным британским плейбоем Джеймсом Хантом доводит обоих до предела возможностей.",
    country: ["UK", "Germany", "USA"],
    director: "Ron Howard"
  },
  {
    title: "Короткий срок 12",
    year: 2013,
    genres: ["Drama"],
    runtime: "1h 36m",
    rating: 4.2,
    poster: "/posters/term.jpg",
    backdrop: "/backdrops/term.jpg",
    description: "Грейс, чуткая молодая руководительница приюта для трудных подростков, помогает детям из группы риска, но появление нового подопечного пробуждает воспоминания о её собственном тяжёлом прошлом, и её прочная защитная броня начинает давать трещину.",
    country: ["USA"],
    director: "Destin Daniel Cretton"
  },
  {
    title: "Волк с Уолл-стрит",
    year: 2013,
    genres: ["Crime", "Drama", "Comedy"],
    runtime: "3h 00m",
    rating: 4.1,
    poster: "/posters/wallstreet.jpg",
    backdrop: "/backdrops/wallstreet.jpg",
    description: "Стремительное восхождение биржевого брокера к баснословному богатству через мошенничество и коррупцию на Уолл-стрит заканчивается столь же эффектным падением.",
    country: ["USA"],
    director: "Martin Scorsese"
  },
  {
    title: "Исчезнувшая",
    year: 2014,
    genres: ["Drama", "Mystery", "Thriller"],
    runtime: "2h 29m",
    rating: 4.0,
    poster: "/posters/gonegirl.jpg",
    backdrop: "/backdrops/gonegirl.jpg",
    description: "Мужчина становится главным подозреваемым в загадочном исчезновении жены, пока СМИ и полиция копаются в тёмных секретах их брака.",
    country: ["USA"],
    director: "David Fincher"
  },
  {
    title: "Интерстеллар",
    year: 2014,
    genres: ["Adventure", "Drama", "Science Fiction"],
    runtime: "2h 49m",
    rating: 4.4,
    poster: "/posters/interstellar.jpg",
    backdrop: "/backdrops/interstellar.jpg",
    description: "Команда исследователей отправляется через червоточину на поиски новой обитаемой планеты, поскольку Земля всё меньше способна поддерживать жизнь человечества.",
    country: ["USA", "UK"],
    director: "Christopher Nolan"
  },
  {
    title: "Мамочка",
    year: 2014,
    genres: ["Drama"],
    runtime: "2h 18m",
    rating: 4.3,
    poster: "/posters/mommy.jpg",
    backdrop: "/backdrops/mommy.jpg",
    description: "Странноватый сосед даёт надежду недавно овдовевшей женщине, которая пытается воспитывать непредсказуемого, а порой и агрессивного подростка-сына.",
    country: ["Canada"],
    director: "Xavier Dolan"
  },
  {
    title: "Отель «Гранд Будапешт»",
    year: 2014,
    genres: ["Comedy", "Drama"],
    runtime: "1h 39m",
    rating: 4.2,
    poster: "/posters/budapest.jpg",
    backdrop: "/backdrops/budapest.jpg",
    description: "Легендарный консьерж и его преданный лобби-бой оказываются втянуты в историю с украденной картиной, огромным наследством и противостоянием со зловещей семьёй в знаменитом европейском отеле.",
    country: ["Germany", "USA"],
    director: "Wes Anderson"
  },
  {
    title: "Одержимость",
    year: 2014,
    genres: ["Drama", "Music"],
    runtime: "1h 47m",
    rating: 4.3,
    poster: "/posters/whiplash.jpg",
    backdrop: "/backdrops/whiplash.jpg",
    description: "Амбициозный молодой барабанщик поступает в безжалостную музыкальную консерваторию, где жестокий и требовательный преподаватель толкает его то ли к величию, то ли к нервному срыву.",
    country: ["USA"],
    director: "Damien Chazelle"
  },
  {
    title: "Зимняя спячка",
    year: 2014,
    genres: ["Drama"],
    runtime: "3h 16m",
    rating: 4.0,
    poster: "/posters/wintersleep.jpg",
    backdrop: "/backdrops/wintersleep.jpg",
    description: "В анатолийской степи бывший актёр Айдын управляет небольшим отелем вместе с молодой женой Нихаль, с которой у него натянутые отношения, и сестрой Неджлой, переживающей развод; с приближением зимы Айдын вступает в конфликт с арендаторами, продолжая писать колонки для местной газеты.",
    country: ["France", "Germany", "Turkey"],
    director: "Nuri Bilge Ceylan"
  },
  {
    title: "Безумный Макс: Дорога ярости",
    year: 2015,
    genres: ["Action", "Adventure", "Science Fiction"],
    runtime: "2h 00m",
    rating: 4.1,
    poster: "/posters/madmax.jpg",
    backdrop: "/backdrops/madmax.jpg",
    description: "В постапокалиптической пустоши скиталец и мятежная воительница возглавляют отчаянный побег от тиранического военачальника через пустыню.",
    country: ["Australia", "USA"],
    director: "George Miller"
  },
  {
    title: "Сестрёнка",
    year: 2015,
    genres: ["Drama"],
    runtime: "2h 08m",
    rating: 4.1,
    poster: "/posters/ourlittlesister.jpg",
    backdrop: "/backdrops/ourlittlesister.jpg",
    description: "К трём сёстрам, живущим в Камакуре, после смерти отца присоединяется их юная сводная сестра.",
    country: ["Japan"],
    director: "Hirokazu Koreeda"
  },
  {
    title: "Комната",
    year: 2015,
    genres: ["Drama"],
    runtime: "1h 58m",
    rating: 3.9,
    poster: "/posters/room.jpg",
    backdrop: "/backdrops/room.jpg",
    description: "Мать и её пятилетний сын, годами удерживаемые в плену в одной-единственной комнате, наконец вырываются на свободу в огромный мир, которого мальчик никогда не видел.",
    country: ["Canada", "Ireland", "UK", "USA"],
    director: "Lenny Abrahamson"
  },
  {
    title: "В центре внимания",
    year: 2015,
    genres: ["Drama", "History"],
    runtime: "2h 09m",
    rating: 4.0,
    poster: "/posters/spotlight.jpg",
    backdrop: "/backdrops/spotlight.jpg",
    description: "Команда журналистов Boston Globe раскрывает систематическое сокрытие Католической церковью случаев насилия над детьми со стороны священников.",
    country: ["USA"],
    director: "Tom McCarthy"
  },
  {
    title: "Игра на понижение",
    year: 2015,
    genres: ["Drama", "Comedy"],
    runtime: "2h 11m",
    rating: 3.9,
    poster: "/posters/bigshort.jpg",
    backdrop: "/backdrops/bigshort.jpg",
    description: "История людей, заработавших миллионы на мировом экономическом крахе.",
    country: ["USA"],
    director: "Adam McKay"
  },
  {
    title: "По соображениям совести",
    year: 2016,
    genres: ["War", "Drama", "History"],
    runtime: "2h 19m",
    rating: 3.9,
    poster: "/posters/hacksaw.jpg",
    backdrop: "/backdrops/hacksaw.jpg",
    description: "Глубоко верующий санитар, отказывающийся брать в руки оружие, спасает десятки жизней во время жестокой битвы за Окинаву.",
    country: ["USA", "Australia"],
    director: "Mel Gibson"
  },
  {
    title: "Ла-Ла Ленд",
    year: 2016,
    genres: ["Drama", "Comedy", "Romance"],
    runtime: "2h 09m",
    rating: 4.1,
    poster: "/posters/lalaland.jpg",
    backdrop: "/backdrops/lalaland.jpg",
    description: "Мия, начинающая актриса, разносит кофе кинозвёздам между прослушиваниями, а Себастьян, джазовый музыкант, перебивается случайными выступлениями в захудалых барах; на пути к успеху паре приходится принимать решения, которые ставят под угрозу их хрупкие отношения и мечты, которые они так старались сохранить друг в друге.",
    country: ["USA"],
    director: "Damien Chazelle"
  },
  {
    title: "Невидимый гость",
    year: 2016,
    genres: ["Thriller", "Crime", "Mystery"],
    runtime: "1h 46m",
    rating: 4.0,
    poster: "/posters/guest.jpg",
    backdrop: "/backdrops/guest.jpg",
    description: "Бизнесмен, обвинённый в убийстве, нанимает известного адвоката, чтобы распутать правду, пока его дело не стало безнадёжным.",
    country: ["Spain"],
    director: "Oriol Paulo"
  },
  {
    title: "Бегущий по лезвию 2049",
    year: 2017,
    genres: ["Drama", "Science Fiction"],
    runtime: "2h 44m",
    rating: 4.1,
    poster: "/posters/blade2049.jpg",
    backdrop: "/backdrops/blade2049.jpg",
    description: "Тридцать лет спустя после событий первого фильма новый блейд-раннер, офицер полиции Лос-Анджелеса К, раскрывает давно похороненную тайну, способную ввергнуть остатки общества в хаос, и это открытие приводит его к поискам пропавшего без вести тридцать лет назад Рика Декарда.",
    country: ["Canada", "UK", "USA"],
    director: "Denis Villeneuve"
  },
  {
    title: "Три билборда на границе Эббинга, Миссури",
    year: 2017,
    genres: ["Drama", "Comedy", "Crime"],
    runtime: "1h 55m",
    rating: 4.0,
    poster: "/posters/billboards.jpg",
    backdrop: "/backdrops/billboards.jpg",
    description: "Скорбящая мать арендует три придорожных билборда, чтобы публично обвинить местную полицию в неспособности раскрыть убийство её дочери.",
    country: ["UK", "USA"],
    director: "Martin McDonagh"
  },
  {
    title: "Капернаум",
    year: 2018,
    genres: ["Drama"],
    runtime: "2h 06m",
    rating: 4.0,
    poster: "/posters/capernaum.jpg",
    backdrop: "/backdrops/capernaum.jpg",
    description: "Ливанский мальчик, живущий в нищете, подаёт в суд на собственных родителей за то, что они дали ему жизнь, и в ходе разбирательства раскрываются отчаянные обстоятельства его детства.",
    country: ["Lebanon"],
    director: "Nadine Labaki"
  },
  {
    title: "Гонка века: Форд против Феррари",
    year: 2019,
    genres: ["Drama", "Action", "History"],
    runtime: "2h 32m",
    rating: 4.0,
    poster: "/posters/fordferrari.jpg",
    backdrop: "/backdrops/fordferrari.jpg",
    description: "Американский автоконструктор и отчаянный британский гонщик объединяются, чтобы построить революционный гоночный автомобиль и обойти Ferrari на «24 часах Ле-Мана».",
    country: ["USA", "France"],
    director: "James Mangold"
  },
  {
    title: "Маленькие женщины",
    year: 2019,
    genres: ["Drama", "Romance"],
    runtime: "2h 15m",
    rating: 4.2,
    poster: "/posters/littlewomen.jpg",
    backdrop: "/backdrops/littlewomen.jpg",
    description: "Четыре сестры взрослеют в Америке после Гражданской войны под нежной, но твёрдой опекой любимой матери, и каждая ищет свой собственный путь, преодолевая бедность и потери.",
    country: ["USA"],
    director: "Greta Gerwig"
  },
  {
    title: "Паразиты",
    year: 2019,
    genres: ["Drama", "Thriller", "Comedy"],
    runtime: "2h 12m",
    rating: 4.5,
    poster: "/posters/parasite.jpg",
    backdrop: "/backdrops/parasite.jpg",
    description: "Бедная семья хитростью проникает в дом богатого семейства, запуская цепь событий, которая обнажает жестокую пропасть между бедными и богатыми.",
    country: ["South Korea"],
    director: "Bong Joon Ho"
  },
  {
    title: "Звук металла",
    year: 2019,
    genres: ["Drama", "Music"],
    runtime: "2h 00m",
    rating: 4.1,
    poster: "/posters/soundofmetal.jpg",
    backdrop: "/backdrops/soundofmetal.jpg",
    description: "Барабанщик метал-группы начинает терять слух, и его жизнь переворачивается с ног на голову, когда ему приходится покинуть группу и поселиться в сообществе глухих.",
    country: ["Belgium", "USA"],
    director: "Darius Marder"
  },
]
